### ISSUE TITLE
Missing Description

### ISSUE THREAD

**Issue by ThomasWilczek** [Crankenhaus/guides-and-information#10]
Id would be usefull if every link got a small description to know if it's intresting and usefull for myself or not.

**Comment by dreisen** [comment]
assigning @m-Schlitzer because he's the one authoring the list

**Comment by m-Schlitzer** [comment]
Since this will be helpful to all of us, I will add short descriptions to each of the links and turn them into linked titles, for better oversight.

**Comment by m-Schlitzer** [comment]
Resolved in ed70b0b596de4b7a0eb67bbb55ec4f7125b63a45
